version: '3.8'

services:
  xray:
    image: teddysun/xray:latest
    container_name: vless-xray
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - "./config:/etc/xray:ro"
      - "./data:/app/data:rw"
      - "./logs:/app/logs:rw"
    environment:
      - "TZ=UTC"
    networks:
      - vless-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  vless-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
