#!/bin/bash
# lib/docker_compose_generator.sh
#
# Docker Compose Configuration Generator (v4.3 Unified HAProxy)
# Generates docker-compose.yml dynamically via heredoc (no static files)
#
# Features:
# - Full docker-compose.yml generation via heredoc
# - HAProxy unified TLS termination (ports 443, 1080, 8118)
# - stunnel REMOVED (replaced by HAProxy)
# - Dynamic port management for nginx reverse proxy (9443-9452)
# - Integration with lib/docker_compose_manager.sh
# - PRD v4.1 compliant (no templates, all heredoc)
#
# Version: 4.3.0
# Author: VLESS Development Team
# Date: 2025-10-17

set -euo pipefail

# Configuration
VLESS_DIR="${VLESS_DIR:-/opt/familytraffic}"
DOCKER_COMPOSE_FILE="${VLESS_DIR}/docker-compose.yml"
DOCKER_SUBNET="${DOCKER_SUBNET:-172.20.0.0/16}"
# v5.1: VLESS_PORT is internal port 8443 (HAProxy listens on 443 externally)
VLESS_PORT="${VLESS_PORT:-8443}"

# Logging
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [docker-compose-gen] $*" >&2
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [docker-compose-gen] ERROR: $*" >&2
}

# =============================================================================
# Function: generate_docker_compose
# Description: Generates complete docker-compose.yml via heredoc (v4.3 unified HAProxy)
#
# Parameters:
#   $@ - nginx_ports: Array of ports for nginx reverse proxy (e.g., 9443 9444)
#        NEW in v4.3: ports are 9443-9452 (not 8443-8452)
#        Empty array = no ports exposed (reverse proxy not configured)
#
# Returns:
#   0 on success, 1 on failure
#
# Output:
#   Creates /opt/familytraffic/docker-compose.yml
#
# Example:
#   generate_docker_compose 9443 9444 9445
# =============================================================================
generate_docker_compose() {
    local nginx_ports=("$@")
    local enable_reverse_proxy="${ENABLE_REVERSE_PROXY:-false}"
    local enable_mtproxy="${ENABLE_MTPROXY:-false}"

    log "Generating docker-compose.yml (heredoc-based, v6.0 with MTProxy)"
    log "  VLESS Port: ${VLESS_PORT} (Xray internal port)"
    log "  Docker Subnet: ${DOCKER_SUBNET}"
    log "  Reverse Proxy: ${enable_reverse_proxy}"
    log "  Nginx Ports: ${nginx_ports[*]:-none} (localhost only)"
    log "  MTProxy: ${enable_mtproxy}"

    # Create backup if file exists
    if [ -f "${DOCKER_COMPOSE_FILE}" ]; then
        cp "${DOCKER_COMPOSE_FILE}" "${DOCKER_COMPOSE_FILE}.bak"
        log "  Backup created: ${DOCKER_COMPOSE_FILE}.bak"
    fi

    # Generate nginx ports section (localhost-only, new range 9443-9452)
    local nginx_ports_yaml=""
    if [ ${#nginx_ports[@]} -gt 0 ]; then
        for port in "${nginx_ports[@]}"; do
            nginx_ports_yaml+="
      - \"127.0.0.1:${port}:${port}\""
        done
    else
        # Empty ports array (reverse proxy not configured)
        nginx_ports_yaml=" []  # Empty by default - populated dynamically"
    fi

    # Generate nginx service section conditionally (v5.26)
    local nginx_service_section=""
    if [[ "${enable_reverse_proxy}" == "true" ]]; then
        nginx_service_section=$(cat <<NGINX_SERVICE

  # ===========================================================================
  # Nginx Reverse Proxy Service (v5.26 - Conditional)
  # Site-Specific Reverse Proxy for Blocked Websites
  # ===========================================================================
  nginx:
    image: nginx:alpine
    container_name: vless_nginx_reverseproxy
    restart: unless-stopped
    volumes:
      # Main reverse proxy configs (generated by lib/nginx_config_generator.sh)
      - \${VLESS_DIR}/config/reverse-proxy/:/etc/nginx/conf.d/reverse-proxy/:ro

      # HTTP context config (rate limiting, fail2ban log format)
      # Generated by lib/nginx_config_generator.sh::generate_reverseproxy_http_context()
      - \${VLESS_DIR}/config/reverse-proxy/http_context.conf:/etc/nginx/conf.d/http_context.conf:ro

      # Let's Encrypt certificates (read-only)
      - /etc/letsencrypt:/etc/letsencrypt:ro

      # Logs for fail2ban monitoring
      - \${VLESS_DIR}/logs/nginx/:/var/log/nginx/

    # v4.3 CHANGE: Port mappings now localhost-only (9443-9452, not 8443-8452)
    # Managed dynamically via lib/docker_compose_manager.sh
    ports:${nginx_ports_yaml}

    networks:
      - vless_reality_net

    depends_on:
      - xray

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # Tmpfs mounts for nginx cache (required when running as user: nginx)
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
NGINX_SERVICE
)
    else
        nginx_service_section=$(cat <<'NO_NGINX_SERVICE'

  # ===========================================================================
  # Nginx Reverse Proxy Service: DISABLED (v5.26)
  # Reverse proxy feature was not enabled during installation
  # To enable: reinstall with reverse proxy option enabled
  # ===========================================================================
NO_NGINX_SERVICE
)
    fi

    # Generate MTProxy service section conditionally (v6.0)
    local mtproxy_service_section=""
    if [[ "${enable_mtproxy}" == "true" ]]; then
        # Read MTProxy configuration if exists
        local mtproxy_port="${MTPROXY_PORT:-8443}"
        local mtproxy_stats_port="${MTPROXY_STATS_PORT:-8888}"

        mtproxy_service_section=$(cat <<'MTPROXY_SERVICE'

  # ===========================================================================
  # MTProxy Service (v6.0 - Telegram Proxy)
  # Official Telegram MTProxy for transport obfuscation
  # ===========================================================================
  mtproxy:
    build:
      context: ${VLESS_DIR}
      dockerfile: docker/mtproxy/Dockerfile
    image: vless/mtproxy:latest
    container_name: vless_mtproxy
    restart: unless-stopped
    ports:
      - "8443:8443"                    # MTProxy public port (Telegram traffic)
      - "127.0.0.1:8888:8888"          # Stats endpoint (localhost only)
    volumes:
      - ${VLESS_DIR}/config/mtproxy:/etc/mtproxy:ro
      - ${VLESS_DIR}/logs/mtproxy:/var/log/mtproxy
      - ${VLESS_DIR}/data/mtproxy:/var/lib/mtproxy
    networks:
      - vless_reality_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8443"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
MTPROXY_SERVICE
)
    else
        mtproxy_service_section=$(cat <<'NO_MTPROXY_SERVICE'

  # ===========================================================================
  # MTProxy Service: DISABLED (v6.0)
  # MTProxy was not enabled during installation
  # To enable: run 'sudo vless-mtproxy-setup'
  # ===========================================================================
NO_MTPROXY_SERVICE
)
    fi

    # Generate docker-compose.yml via heredoc (v6.0)
    # Note: 'version' attribute removed (obsolete in Docker Compose v2)
    cat > "${DOCKER_COMPOSE_FILE}" <<EOF
services:
  # ===========================================================================
  # Nginx Service (v5.30 — replaces HAProxy)
  # stream block: Port 443 (ssl_preread SNI routing), 1080/8118 (TLS termination)
  # http block:   Port 8448 (loopback, Tier 2 transports — WS/XHTTP/gRPC)
  # ===========================================================================
  vless_nginx:
    image: nginx:1.27-alpine
    container_name: vless_nginx
    restart: unless-stopped
    networks:
      - vless_reality_net
    cap_add:
      - NET_BIND_SERVICE  # Required: bind ports < 1024 (443, 1080, 8118)
    ports:
      - "443:443"      # HTTPS SNI routing (stream, ssl_preread — no TLS termination)
      - "1080:1080"    # SOCKS5 with TLS termination
      - "8118:8118"    # HTTP proxy with TLS termination
    volumes:
      - \${VLESS_DIR}/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - \${VLESS_DIR}/logs/nginx/:/var/log/nginx/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - xray
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # ===========================================================================
  # Xray-core Service (VLESS Reality + Proxy Inbounds)
  # ===========================================================================
  xray:
    image: teddysun/xray:24.11.30
    container_name: vless_xray
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ${VLESS_DIR}/config/xray_config.json:/etc/xray/config.json:ro
      - ${VLESS_DIR}/logs/xray/:/var/log/xray/
    expose:
      # Ports exposed ONLY within Docker network (not to host)
      # vless_nginx accesses these via service name: vless_xray:PORT
      - "8443"   # VLESS Reality inbound (ssl_preread passthrough from nginx port 443)
      - "10800"  # SOCKS5 proxy (plaintext, Nginx terminates TLS on port 1080)
      - "18118"  # HTTP proxy (plaintext, Nginx terminates TLS on port 8118)
      - "8444"   # VLESS WebSocket plaintext (Nginx Tier 2 http block → Xray, v5.30)
      - "8445"   # VLESS XHTTP/SplitHTTP plaintext (Nginx Tier 2 http block → Xray, v5.31)
      - "8446"   # VLESS gRPC plaintext (Nginx Tier 2 http block → Xray, v5.32)
      # Note: expose only publishes within Docker network — NOT to host ports
    networks:
      - vless_reality_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
${nginx_service_section}

  # ===========================================================================
  # Certbot Nginx Service (v4.3 NEW - ACME HTTP-01 Challenges)
  # Runs only when needed for certificate acquisition
  # ===========================================================================
  certbot_nginx:
    image: nginx:alpine
    container_name: vless_certbot_nginx
    restart: "no"  # Do not restart automatically
    network_mode: host  # Direct access to port 80
    volumes:
      - ${VLESS_DIR}/config/certbot-nginx/:/etc/nginx/conf.d/:ro
      - /var/www/certbot:/var/www/certbot:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - certbot  # Start only with: docker-compose --profile certbot up

  # ===========================================================================
  # Nginx Fake Site Service (VLESS Reality Fallback)
  # Shows legitimate website for invalid VLESS connections
  # ===========================================================================
  fake-site:
    image: nginx:alpine
    container_name: vless_fake_site
    restart: unless-stopped
    user: nginx
    volumes:
      - ${VLESS_DIR}/fake-site/:/etc/nginx/conf.d/:ro
      - ${VLESS_DIR}/logs/fake-site/:/var/log/nginx/
    networks:
      - vless_reality_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Tmpfs mounts for nginx cache (required when running as user: nginx)
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
${mtproxy_service_section}

# =============================================================================
# Networks
# =============================================================================
# Network is created externally by orchestrator.sh (Step 9: create_docker_network)
# Docker Compose uses existing network instead of trying to manage it
networks:
  vless_reality_net:
    external: true
EOF

    local exit_code=$?

    if [ $exit_code -eq 0 ]; then
        log "✅ docker-compose.yml generated successfully"
        log "  Location: ${DOCKER_COMPOSE_FILE}"
        return 0
    else
        log_error "❌ Failed to generate docker-compose.yml"

        # Restore backup if generation failed
        if [ -f "${DOCKER_COMPOSE_FILE}.bak" ]; then
            mv "${DOCKER_COMPOSE_FILE}.bak" "${DOCKER_COMPOSE_FILE}"
            log "  Backup restored"
        fi

        return 1
    fi
}

# =============================================================================
# Function: validate_docker_compose
# Description: Validates generated docker-compose.yml
#
# Returns:
#   0 if valid, 1 if invalid
# =============================================================================
validate_docker_compose() {
    log "Validating docker-compose.yml..."

    if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
        log_error "docker-compose.yml not found: ${DOCKER_COMPOSE_FILE}"
        return 1
    fi

    # Validate YAML syntax
    if command -v docker-compose &> /dev/null; then
        if docker-compose -f "${DOCKER_COMPOSE_FILE}" config > /dev/null 2>&1; then
            log "✅ docker-compose.yml is valid"
            return 0
        else
            log_error "❌ docker-compose.yml has syntax errors"
            docker-compose -f "${DOCKER_COMPOSE_FILE}" config 2>&1 | head -10
            return 1
        fi
    elif command -v docker &> /dev/null && docker compose version &> /dev/null; then
        if docker compose -f "${DOCKER_COMPOSE_FILE}" config > /dev/null 2>&1; then
            log "✅ docker-compose.yml is valid"
            return 0
        else
            log_error "❌ docker-compose.yml has syntax errors"
            docker compose -f "${DOCKER_COMPOSE_FILE}" config 2>&1 | head -10
            return 1
        fi
    else
        log "⚠️  Warning: docker-compose not found, skipping validation"
        return 0
    fi
}

# =============================================================================
# Function: get_current_nginx_ports
# Description: Extracts current nginx ports from docker-compose.yml (v4.3)
#
# Returns:
#   Array of ports (one per line) to stdout
#
# Note: v4.3 ports are 9443-9452 with localhost binding (127.0.0.1:PORT:PORT)
# =============================================================================
get_current_nginx_ports() {
    if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
        return 0
    fi

    # Extract ports from nginx service using grep/sed
    # v4.3 Format: - "127.0.0.1:9443:9443" → 9443
    # v5.21: Increased -A 20 → -A 30 to ensure ports section is captured
    grep -A 30 "^  nginx:" "${DOCKER_COMPOSE_FILE}" \
        | grep -E '^\s+- "(127\.0\.0\.1:)?[0-9]+:[0-9]+"' \
        | sed -E 's/.*"(127\.0\.0\.1:)?([0-9]+):[0-9]+".*/\2/' \
        | grep -E '^94[4-5][0-9]$' \
        || true
}

# =============================================================================
# Main execution (for testing)
# =============================================================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Script is being executed directly (not sourced)

    if [ $# -lt 1 ]; then
        echo "Usage: $0 <command> [options]"
        echo ""
        echo "Commands:"
        echo "  generate [PORT1 PORT2 ...]  - Generate docker-compose.yml with nginx ports"
        echo "  validate                     - Validate existing docker-compose.yml"
        echo "  get-ports                    - Show current nginx ports"
        echo ""
        echo "Examples:"
        echo "  $0 generate                 # No nginx ports (reverse proxy not configured)"
        echo "  $0 generate 9443 9444       # With 2 nginx ports (v4.3)"
        echo "  $0 validate                 # Validate syntax"
        echo "  $0 get-ports                # List current ports"
        exit 1
    fi

    command="$1"
    shift

    case "$command" in
        generate)
            generate_docker_compose "$@" && validate_docker_compose
            ;;
        validate)
            validate_docker_compose
            ;;
        get-ports)
            get_current_nginx_ports
            ;;
        *)
            log_error "Unknown command: $command"
            exit 1
            ;;
    esac
fi
