version: '3.8'

services:
  xray:
    image: teddysun/xray:latest
    container_name: vless-xray
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /opt/vless/config:/etc/xray:ro
      - /opt/vless/logs:/var/log/xray
      - /opt/vless/certs:/opt/certs:ro
    environment:
      - TZ=UTC
    networks:
      - vless-network
    healthcheck:
      test: ["CMD", "xray", "test", "-c", "/etc/xray/config.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: vless-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/vless/logs:/var/log/nginx
    environment:
      - TZ=UTC
    networks:
      - vless-network
    depends_on:
      - xray
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m
      - /tmp:noexec,nosuid,size=10m
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: vless-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Daily at 4 AM
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=
      - TZ=UTC
    networks:
      - vless-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    profiles:
      - auto-update

networks:
  vless-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: vless-br0

volumes:
  xray-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/vless/config

  xray-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/vless/logs

  xray-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/vless/certs