version: '3.8'

services:
  fake-site:
    image: nginx:alpine
    container_name: vless-fake-site
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./fake-site/html:/usr/share/nginx/html:ro
      - ./fake-site/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fake-net
    labels:
      - "com.vless.service=fake-site"
      - "com.vless.description=Fallback decoy website"

networks:
  fake-net:
    driver: bridge